### ISSUE TITLE
Fail to launch a new scenario with the latest version

### ISSUE THREAD

**Issue by tomoyamachi** [kubernetes-simulator/simulator#261] opened 2020-02-29 06:17 UTC
**Describe the bug**

Fail to launch a new scenario when I have another running scenario.

**To Reproduce**
1. Run a `controlplane/simulator:0.6.0` container 
2. Create infra etc...
3. command run `simulator scenario launch <scenario>` in container
4. command run `simulator scenario launch <another-scenario>` in container

```
launch@launch:/app[0]$ simulator scenario launch secret-tank-desant
INFO[2020-02-28T07:57:32Z] Ensuring there is a simulator keypair
...
INFO[2020-02-28T07:57:37Z] Keyscanning bastion and updating known hosts  BastionIP=54.199.232.73
INFO[2020-02-28T07:57:37Z] Setting up the scenario on the cluster        Scenario="Secret Tank Desant"
INFO[2020-02-28T07:57:40Z] [./perturb.sh] Installed scenario found: secret-high-ground$
ERRO[2020-02-28T07:57:40Z] Scenario secret-high-ground already deployed  Args="[--master 172.31.2.142 --bastion 54.199.232.73 --nodes 172.31.2.25,172.31.2.63 secret-tank-desant]" Command=./perturb.sh
ERRO[2020-02-28T07:57:40Z] Scenario clash error from perturb.sh
```

**Expected behavior**
We can run a new scenario if ran another scenario.

**Environment (please complete the following information):**
 - OS: macOS Catalina
 - Docker: 19.03.5
 - Version of simulator[e.g. master, release number] : 

```
simulator version
INFO[2020-02-29T06:12:39Z] version
INFO[2020-02-29T06:12:39Z] git commit
INFO[2020-02-29T06:12:39Z] build date 2020-02-25T16:25:10Z
```

**Comment by raoulmillais** [comment] 2020-03-03 10:51
This in our roadmap as "cluster reset" .. the problem is that the perturb scripts could do absolutely anything to the cluster and we can't guarantee that 2 scenarios won't inadvertently affect one another. So adding a `--force` option could cause weird behviours.  I think we will try to implement AMI snapshotting or similar to enable reverting the cluster to a known clean slate

**Comment by tomoyamachi** [comment] 2020-03-03 16:13
I understand.
I run `simulator infra create` and `simulator infra destroy` when starting each scenario.

**Comment by jondkent** [comment] 2021-03-04 11:52
Closing as outdated

**Closed by jondkent** 2021-03-04 11:52 UTC
Labels: duplicate, onHold
